
def varas() -> dict:
    
    return {
    "1ª Vara do Trabalho de Boa Vista": "#VTBV1-1",
    "2ª Vara do Trabalho de Boa Vista": "#VTBV2-1",
    "3ª Vara do Trabalho de Boa Vista": "#VTBV3-1",
    "51ª Vara Digital do Núcleo de Justiça 4.0 - RR": "#51VDRR-1",
    "52ª Vara Digital do Núcleo de Justiça 4.0 - RR": "#52VDRR-1",
    "53ª Vara Digital do Núcleo de Justiça 4.0 - RR": "#53VDRR-1",
    "CEJUSC - BOA VISTA": "#CBV-1",
    "1ª Vara do Trabalho de Coari": "#1VTC-1",
    "1ª Vara do Trabalho de Eirunepé": "#VTE-1",
    "1ª Vara do Trabalho de Humaitá": "#1VTH-1",
    "1ª Vara do Trabalho de Itacoatiara": "#VTI-1",
    "1ª Vara do Trabalho de Lábrea": "#1VTL-1",
    "1ª Vara do Trabalho de Manacapuru": "#1VTM-1",
    "1ª Vara do Trabalho de Manaus": "#VT1",
    "2ª Vara do Trabalho de Manaus": "#VT2",
    "3ª Vara do Trabalho de Manaus": "#VT3",
    "4ª Vara do Trabalho de Manaus": "#VT4",
    "5ª Vara do Trabalho de Manaus": "#VT5",
    "6ª Vara do Trabalho de Manaus": "#VT6",
    "7ª Vara do Trabalho de Manaus": "#VT7",
    "8ª Vara do Trabalho de Manaus": "#VT8",
    "9ª Vara do Trabalho de Manaus": "#VT9",
    "10ª Vara do Trabalho de Manaus": "#VTL-10",
    "11ª Vara do Trabalho de Manaus": "#VTL-11",
    "12ª Vara do Trabalho de Manaus": "#VTL-12",
    "13ª Vara do Trabalho de Manaus": "#VTL-13",
    "14ª Vara do Trabalho de Manaus": "#VTL-14",
    "15ª Vara do Trabalho de Manaus": "#VTL-15",
    "16ª Vara do Trabalho de Manaus": "#VTL-16",
    "17ª Vara do Trabalho de Manaus": "#VTL-17",
    "18ª Vara do Trabalho de Manaus": "#VTL-18",
    "19ª Vara do Trabalho de Manaus": "#VTL-19",
    "1ª Vara Digital do Núcleo de Justiça 4.0 - AM": "1VDAM-1",
    "2ª Vara Digital do Núcleo de Justiça 4.0 - AM": "2VDAM-1",
    "3ª Vara Digital do Núcleo de Justiça 4.0 - AM": "3VDAM-1",
    "4ª Vara Digital do Núcleo de Justiça 4.0 - AM": "4VDAM-1",
    "5ª Vara Digital do Núcleo de Justiça 4.0 - AM": "5VDAM-1",
    "6ª Vara Digital do Núcleo de Justiça 4.0 - AM": "6VDAM-1",
    "7ª Vara Digital do Núcleo de Justiça 4.0 - AM": "7VDAM-1",
    "8ª Vara Digital do Núcleo de Justiça 4.0 - AM": "8VDAM-1",
    "9ª Vara Digital do Núcleo de Justiça 4.0 - AM": "9VDAM-1",
    "10ª Vara Digital do Núcleo de Justiça 4.0 - AM": "10VDAM-1",
    "11ª Vara Digital do Núcleo de Justiça 4.0 - AM": "11VDAM-1",
    "12ª Vara Digital do Núcleo de Justiça 4.0 - AM": "12VDAM-1",
    "13ª Vara Digital do Núcleo de Justiça 4.0 - AM": "13VDAM-1",
    "14ª Vara Digital do Núcleo de Justiça 4.0 - AM": "14VDAM-1",
    "15ª Vara Digital do Núcleo de Justiça 4.0 - AM": "15VDAM-1",
    "16ª Vara Digital do Núcleo de Justiça 4.0 - AM": "16VDAM-1",
    "17ª Vara Digital do Núcleo de Justiça 4.0 - AM": "17VDAM-1",
    "18ª Vara Digital do Núcleo de Justiça 4.0 - AM": "18VDAM-1",
    "19ª Vara Digital do Núcleo de Justiça 4.0 - AM": "19VDAM-1",
    "Secretaria de Execução da Fazenda Pública": "#SP-1",
    "SEÇÃO DE HASTAS PÚBLICAS- SEHASP": "#DIHASP-1",
    "CEJUSC-JT 1º grau": "#CEJUSC1-1",
    "Divisão de Execução Concentrada": "#CONAE-1",
    "Divisão de Pesquisa Patrimonial": "#DIPEP-1",
    "Projeto Garimpo - 1º Grau": "#PG-1",
    "Corregedoria-Geral;": "#CNAC-1",
    "1ª Vara do Trabalho de Parintins": "#VTP-1",
    "1ª Vara do Trabalho de Presidente Figueiredo": "#1VTPF-1",
    "1ª Vara do Trabalho de Tabatinga": "#1VTT-1",
    "1ª Vara do Trabalho de Tefé": "#1VTTF-1"
}